### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by TimLiu98** [ManuelPalermo/X-Ray-ConvNet#2]
Hi, Bro, when running main.py, it shows that:

IndexError: list index out of range

Maybe the problem is here, but I'm not sure about it.

val_labels = np.vstack(val_data.apply(lambda x: max(x[1].split())).values).astype(np.int8)[:self.nval]

Do u have any thoughts？

**Comment by ManuelPalermo** [comment]
Hi, could you please post the error trace it would help pinpointing the problem.

Could you also confirm that:
-You have downloaded the data correctly from https://nihcc.app.box.com/v/ChestXray-NIHCC/folder/37178474737 and placed it in the correct directories. You can follow this readme (https://github.com/ManuelPalermo/X-Ray-ConvNet/blob/master/database/readme.txt).
-You have run the PreprocessData.py script to prepare the data before running the Main.py.

**Comment by TimLiu98** [comment]
Hi, I just realized that I had changed your txt files to csv before. After using txt files, this problem was solved and I am trying to find the reason now. For in PreprocessData.py, I also use csv files.

**Comment by ManuelPalermo** [comment]
From what i see it shouldn't make a difference as long as you correctly change the name of the files when calling them in the script(.txt to .csv), as I am already reading the .txt file as is it was a .csv.

But if changing to .txt solves your problems it should be better to work with that, although its not the cleanest way.

Let me know if you have any more problems.

**Comment by TimLiu98** [comment]
Thanks bro, I think I know it know, I use Excel to change format before, but your txt files do NOT have any comma, so I changed the name directly and the problem solved.
