### ISSUE TITLE
dataset/train.txt

### ISSUE THREAD

**Issue by AymunTariq** [ManuelPalermo/X-Ray-ConvNet#5]
Hi, I had a question Where in the code files did you change the 14 labels into 2 that is 0 for normal and 1 for ab normal? Please explain that, also if you can provide an email address where one can contact you, it would be great

**Comment by ManuelPalermo** [comment]
Hi, this is done the dataloader (https://github.com/ManuelPalermo/X-Ray-ConvNet/blob/master/DataLoader.py) on line 24:
```python
train_labels = np.vstack(train_data.apply(lambda x: max(x[1].split())).values).astype(np.int8)[:self.ntrain]
```
max( x[1].split() )   ->   The max operation will result in 0 if there are no abnormalities, or 1 for >1 abnormalities.
