### ISSUE TITLE
Precent2Retrain

### ISSUE THREAD

**Issue by ghost** [ManuelPalermo/X-Ray-ConvNet#6]
Hi, bro, where did you use the Percent2Retrain? I cannot find.

Also, I also have another confuse point, I had comment it on my closed issue, could u pls check it when u are free?

**Comment by ManuelPalermo** [comment]
(Sorry, did not receive notification)

I used the "Percent2Retrain" when initializing the pretrained models (for example):
https://github.com/ManuelPalermo/X-Ray-ConvNet/blob/1f291a0062d8bbcc230759775bac2a8cf7eccf0b/CNN_Model.py#L42-L45

It just selects the corresponding percentage of layers which should not be trained.
